-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) as TOTAL_SALES
FROM  USED_GOODS_BOARD as B 
JOIN USED_GOODS_USER as U ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS ="DONE"
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3 asc;