SELECT SUM(g.SCORE) as SCORE
,g.EMP_NO,	e.EMP_NAME,	e.POSITION,	e.EMAIL
FROM HR_GRADE as g JOIN HR_EMPLOYEES as e
ON g.EMP_NO = e.EMP_NO
WHERE g.YEAR = '2022'
GROUP BY g.EMP_NO , g.YEAR
ORDER BY 1 desc
LIMIT 1
;